### PR TITLE
MINOR: Add http request return

### PR DESCRIPTION
**Pull request by schegi**
Add functionality for http-request return to client native

### CODE REVIEW

**Comment by oktalz** [comment]
@schegi when i resolve issues we have in this PR with go.mod (i just resolved it by using most recent models and config-parser)

I got in a state that tests are failing

to be exact these checks are failing
```
if *r.ReturnContentType != `"text/plain"` {
	t.Errorf("%v: ReturnContentType not text/plain: %v", *r.Index, *r.ReturnContentType)
}
if r.ReturnContent != `"My content"` {
	t.Errorf(`%v: ReturnContent not "My content": %v`, *r.Index, r.ReturnContent)
}
```

this is believe due to unquoting in config-parser
https://github.com/haproxytech/config-parser/blob/f49a3c18726233239666f7623a53c7ec7ba8a7d6/parsers/http/actions/return.go#L102

this unquoting is actually something i do not prefer in config-parser because of this situation. 
I thought it was OK when we merged PR in config-parser, but as i saw here tests also in CN checks a bit different types of usage.

End result (when calling Result() ) receives quotes, but internally when used in CN, when you read structures it will lead to different response

Do you mind if we correct this behavior in config-parser (remove quote and unquote functions) ?

**Comment by schegi** [comment]
I don't mind at all as long as this feature makes it to dataplane API. But i think i had done this unquoting due to problems with the tests in the config-parser, cause some of the fields in the http-request return stetments in the config needed to be quoted, e.g. content-type and content.
How do we work around that?

**Comment by oktalz** [comment]
Today I will take a look at the tests and improve them if needed. (and also update here)
tests shouldn't be an obstacle to implement this/any feature.

**Comment by schegi** [comment]
Was not really problems with the test but with the actually serialzed/deserialized line. content and content type might be quoted in the haproxy.cfg and we do not want to keep the quotes when deserialized to the object field, but we need content/content-type to be quoted when serializedfrom object to haproxy.cfg.

**Comment by oktalz** [comment]
> content and content type might be quoted

in haproxy config file actually almost anything can be like that, 
you can even use ENV var in there. its not only related to this specific parser. 
(similarly to bash scripts)

That is why i will remove unquoting. 
(I would even go so far to say I missed this during review of config-parser PR)
another reason why this is needed is because you can quote in multiple ways: strong and weak quoting
see https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#2.2


Unfortunately that would mean that user needs to take care of this.
Currently, in dataplaneapi, for most things quoting is not allowed due to how regex's were written, but are starting to expand capabilities of dataplaneapi to accept this.

as you saw we also have option to generate 2 types of tests `ok` and `"ok"` precisely because recently we figure it out that config-parser had issues with handling quoted data (splitting was done if space was in "" and that was an issue).
so every parser just treats the data as normal (includes quotes) and client native and dataplane also pass the checking for this to user.
User must decide if he want to use it or not, and if he uses quoting then needs to decide what type of quoting to use

**Comment by schegi** [comment]
I see, but wouldn't that mean that something goes in (obj -> config) unqutoted (in the obj) and goes out (config -> obj) quoted. So a full serialize, deserialize will result in different objects. Ok for me but not really consistent.

**Comment by schegi** [comment]
So what do you suggest, i can also do some of the work.

**Comment by oktalz** [comment]
@schegi I've updated config-parser (https://github.com/haproxytech/config-parser/commit/9a9a56b2f9d2ad1309af323e3e97b8664b6eb4d1)
removed unquoting and quoting in that parser.
this is consistent with any other parser that also does not handle quoting (it is up to a user to decide what he wants to use and if he want to use it)

added also additional test there https://github.com/haproxytech/config-parser/blob/master/types/types-other.go#L306
just to check that both types of quoting is allowed

in client-native I have merged your PR (i have updated go.mod file), so this PR can be closed

**Pull request closed without merging**
