### PR TITLE
FEATURE/MINOR: runtime: add acl support

### PR DESCRIPTION
**Pull request by thomas-kaltenbach**
Hi haproxy maintainers,

I played around with your cool runtime client and I noticed that currently it is not possible to add acl entires to a file which we need to maintain dynamically.

Therefore I created `acls.go` similar to `maps.go`. So it's possible to execute followed commands:
```
show acl
show acl %s
get acl #%s %s
add acl #%s %s
del acl #%s %s
```

It seems the [models/alc.go](https://github.com/haproxytech/models/blob/ea0dd4a520f93b8617fab64379f9dd68f6ef9af5/acl.go) is created for the configuration and not for the runtime. I created new local types. In case you are interested for this PR I can also create a PR to add these types to the model repo.

I look forward to your feedback.

Regards,
Thomas

PS: I also noticed that there are no tests for the runtime. So I tested the functionality with the followed coding:
```
package main

import (
	"log"

	"github.com/haproxytech/client-native/v2/runtime"
)

func main() {
	client := runtime.SingleRuntime{}
	err := client.Init("/etc/haproxy/socket/stats.sock", 0, 0)
	if err != nil {
		log.Println(err)
		return
	}

	// show all acls
	acls, err := client.ShowACLS()
	if err != nil {
		log.Println(err)
		return
	}
	for _, acl := range acls {
		log.Println(*acl)
	}

	// query for a specific acl with name
	acl, err := client.GetACL("src")
	if err != nil {
		log.Println(err)
		return
	}
	log.Println(acl)

	// query all file entries of acls with files
	lastACLFile := ""
	for _, acl := range acls {
		if acl.File != "" {
			lastACLFile = acl.File
			log.Printf("Found acl loaded form file '%s'", acl.File)
			aclFileEntries, err := client.ShowACLFileEntries(acl.File)
			if err != nil {
				log.Println(err)
			}
			if len(aclFileEntries) != 0 {
				log.Println("with followed entries: ")
				for _, entry := range aclFileEntries {
					log.Println(entry)
				}
			}
		}
	}

	// query acl with file
	acl, err = client.GetACL(lastACLFile)
	if err != nil {
		log.Println(err)
		return
	}
	log.Println(acl)

	// add acl entry
	err = client.AddACLFileEntry(acl.ID, "10.10.10.1")
	if err != nil {
		log.Println(err)
		return
	}

	// check if specific entry exists
	entry, err := client.GetACLFileEntry(acl.ID, "10.10.10.1")
	if err != nil {
		log.Println(err)
		return
	}
	if entry != nil {
		log.Println(entry)
	}

	// delete specific entry
	err = client.DeleteACLFileEntry(acl.ID, "10.10.10.1")
	if err != nil {
		log.Println(err)
		return
	}
}
```

### CODE REVIEW

**Comment by oktalz** [comment]
hi , @thomas-kaltenbach 
thanks for this, please allow some time for review ( should be soon :))

in regards to 
> It seems the models/alc.go is created for the configuration and not for the runtime. I created new local types. In case you are interested for this PR I can also create a PR to add these types to the model repo.

in general, since this is a nice feature this will probably also be exposed in [dataplaneapi](https://github.com/haproxytech/dataplaneapi) (on runtime endpoints), therefore we need 
models (and [specification](https://github.com/haproxytech/dataplaneapi-specification)) to include this, 
but I will get back to you soon on with feedback.

**Comment by thomas-kaltenbach** [comment]
Thanks for the quick response!
I look forward to your feedback.

**Comment by thomas-kaltenbach** [comment]
Hi @oktalz,
because this is an important functionality for us we would like to add unit tests to ensure the functionality.
From my perspective we have two possibilities.
1.	Create a `MockServer` which creates a Socket and within the tests you can define what the socket should response
2.	Mock the function `SingleRuntime.Execute()`, a Interface is needed or the ability to add change function definition of Execute()  `SingleRuntime.Execute = func(url string) string { …  }`

I would prefer the first possibility, what is your opinion?

**Comment by aiharos** [comment]
Hi @thomas-kaltenbach

Thank you for the effort and contribution!

As @oktalz mentioned, in order for this functionality to be complete and follow the same conventions as other features, we would like to have this implemented through the full stack - starting with the specification (which will introduce the models and probably remove the need for structs), then this type MR here, and finally a dataplaneapi MR that would expose this feature through the API. 

If you feel like taking on the other 2 MRs in addition to this one - let us know, we'll be happy to review and merge when ready.

A couple more notes: as part of adding the SSL cert management feature we've introduced a new internal Storage interface to centralize handling files, so we've migrated a part of the current maps implementation to that, and we would encourage using the Storage interface for filesystem-based operation for this MR as well. The dataplaneapi MR would ideally also contain e2e tests, and as for the unit tests I'm interested in hearing @oktalz thoughts too.

**Comment by oktalz** [comment]
@thomas-kaltenbach  first, I'm sorry about not responding sooner, with holidays and upcoming dataplaneapi release this was delayed a bit. And one other reason was we were designing a bit how files outside of configuration can be configured via dataplane and that directly impacts this MR in a way.

first of all as you said `models/alc.go` are not ideal since we have a different representation/usage on runtime. 
models.ACl are primarily for acl ccommands, not files
Ideally everything added in client-native will end up in dataplaneapi as well.

that means that models for 

``` Go
ACLFile ....
type ACLFiles []*ACLFile
type ACLFileEntry
```

also needs to be created in dataplane specification (and then used in client native as such)
if you take a look at https://github.com/haproxytech/models/blob/master/map.go it is very similar to ACLFile you created (but it uses `StorageName`) names can stay the same since it does not conflict with `models.ACL` struct

Storage is not to important for this MR (this handles only runtime part), but naming should be consistent with other resources. Also if we have models set like that, we can reuse this to add support for new endpoints that are handling acl files (so not just acl commands) in same way as maps are handled

just a note, PR is only needed for `dataplane-specification` project, `models` itself will generate automatically with our bot

## Tests

Currently I would prefer option 1 also. 
Reason is that soon we will add proper e2e testing (very similar to what dataplane itself already have) to this project also and it would be much easier to migrate that kind of test in future to it

**Comment by thomas-kaltenbach** [comment]
OK nice, I created PR https://github.com/haproxytech/dataplaneapi-specification/pull/28

If I am understand it right, when this PR https://github.com/haproxytech/dataplaneapi-specification/pull/28 is merged the models are generated and I will use the right ones.
In addition I started with the unit test and I will push both when I am ready.

Thanks and regards,
Thomas

**Comment by thomas-kaltenbach** [comment]
fyi @oktalz, I added now the unit tests.

**Comment by oktalz** [comment]
@thomas-kaltenbach great !

 (https://github.com/haproxytech/dataplaneapi-specification/commit/5c5ec1e633afc8025e730d654f50c10699e9fcbb) and models were automatically created (https://github.com/haproxytech/models/commit/67ae4dc94045943f6406e71f9b72deb7d6f2c744)
 
 so only thing to to is to use them instead of local ones

**Comment by oktalz** [comment]
sorry, forgot about those, added them in the definitions also
new models have them (https://github.com/haproxytech/models/commit/32de531b38f275c31f7f6795115f897b66176b67)

**Comment by thomas-kaltenbach** [comment]
@oktalz 
I am happy, its ready and looking forward to your feedback :)

**Pull request merged**
