### PR TITLE
fix invalid reflect call for UniqueIDHeader

### LINKED ISSUE #42: Invalid reflect call in configuration/configuration.go:setFieldValue
https://github.com/haproxytech/client-native/blob/v2.0.2/configuration/configuration.go#L1485-L1502

in `setFieldValue` `field.Elem().Value()` is called to get the value of the frontends `UniqueIdHeader` field. This field is type string, so calling `Elem()` on it results in a panic.

```
panic: reflect: call of reflect.Value.Elem on string Value [recovered]
        panic: reflect: call of reflect.Value.Elem on string Value

goroutine 9 [running]:
testing.tRunner.func1.1(0x184a180, 0xc000465220)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:940 +0x4dc
testing.tRunner.func1(0xc000165200)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:943 +0x317
panic(0x184a180, 0xc000465220)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:975 +0x41b
reflect.Value.Elem(0x1826260, 0xc000d5c138, 0x198, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/reflect/value.go:820 +0x3b5
github.com/haproxytech/client-native/v2/configuration.setFieldValue(0x18ed2bb, 0x8, 0xc00015d241, 0x9, 0x1809847, 0xe, 0x1826260, 0xc000d5c138, 0x198, 0xc000ff2450, ...)
        /Users/z003tt1/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.0.2/configuration/configuration.go:1496 +0xdfde
github.com/haproxytech/client-native/v2/configuration.CreateEditSection(0x18d3580, 0xc000d5c000, 0x18ed2bb, 0x8, 0xc00015d241, 0x9, 0xc000ff2450, 0x0, 0x0)
        /Users/z003tt1/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.0.2/configuration/configuration.go:830 +0x2d7
github.com/haproxytech/client-native/v2/configuration.(*Client).createSection(0xc00012ca80, 0x18ed2bb, 0x8, 0xc00015d241, 0x9, 0x18d3580, 0xc000d5c000, 0xc0010372f0, 0x24, 0x0, ...)
        /Users/z003tt1/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.0.2/configuration/configuration.go:1705 +0x564
github.com/haproxytech/client-native/v2/configuration.(*Client).CreateFrontend(0xc00012ca80, 0xc000d5c000, 0xc0010372f0, 0x24, 0x0, 0x0, 0x0)
        /Users/z003tt1/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.0.2/configuration/frontend.go:117 +0x1a5
```

### PR DESCRIPTION
**Pull request by fwwieffering**
fixes #42

### CODE REVIEW

**Comment by mjuraga** [comment]
Can you just change the commit message, to follow our guidelines, something like:

`BUG/MINOR: fix invalid reflect call for UniqueIDHeader`

**Comment by fwwieffering** [comment]
@mjuraga updated the commit message

**Comment by fwwieffering** [comment]
@mjuraga could you make a tag that includes this fix?

**Comment by mjuraga** [comment]
@fwwieffering a new release is coming in a couple of days

**Pull request merged**
