### PR TITLE
MINOR: server: serialize proto option in server params

### PR DESCRIPTION
**Pull request by kashifmin**
This depends on https://github.com/haproxytech/dataplaneapi-specification/pull/23/files

### CODE REVIEW

**Comment by mjuraga** [comment]
Hi @kashifmin can you please just change the go.mod file for the models package to point to commit: https://github.com/haproxytech/models/commit/2d2751eb7d52be819ca15dfd65983407471f6e89

**Comment by kashifmin** [comment]
@mjuraga I have rebased to master & updated models to the commit by running `go get github.com/haproxytech/models@2d2751eb7d52be819ca15dfd65983407471f6e89`
But the build seems to be failing due to missing symbols. Is because the commit is not a part of `master` in `models` repo?

**Comment by mjuraga** [comment]
It is because you targeted the specification MR on the v1 branch.

The v1 branch is for maintenance of 1.x versions of dataplaneapi and we just backport bugfixes and some simple features by cherry picking the commits from the master. I have now moved the specification and the models commits to master, so use this commit please: https://github.com/haproxytech/models/commit/404064db6c6c1cb9bd3dc1ca8ac51bad19ff2f26

**Comment by kashifmin** [comment]
@mjuraga I wanted the changes on v1 since the dataplane API version we use refers to v1 of models. 
Anyway, I've updated the models to work with master's commit. It seems to build fine now : )

**Comment by mjuraga** [comment]
Please just update the parseServer function.

**Pull request closed without merging**
