### PR TITLE
MINOR: server: serialize proto option in server params

### PR DESCRIPTION
**Pull request by kashifmin**

### CODE REVIEW

**Comment by kashifmin** [comment]
@mjuraga My previous PR was to an older branch. Have cherry-picked the change to master & tested it locally. 
Thanks.

**Comment by mjuraga** [comment]
Can you please just add the proto option to `SerializeServer` function?

**Comment by kashifmin** [comment]
Have already added proto option in SerializeServer function:
```go
if s.Proto != "" {
	srv.Params = append(srv.Params, &params.ServerOptionValue{Name: "proto", Value: s.Proto})
}
```
Am I missing something?

**Comment by mjuraga** [comment]
I shouldn't be reviewing code before the morning coffee, I meant the `ParseServer` function :/

**Comment by kashifmin** [comment]
Good morning @mjuraga ☕️
Have made the change.

**Pull request merged**
